branch-defaults:
  design_updates:
    environment: whack-2016-team-3-dev
global:
  application_name: whack-2016-team-3
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Python 3.4
  default_region: us-east-1
  profile: eb-cli
  sc: git
